---
sudo:             false
dist:             bionic
language:         ruby
cache:            bundler
install:
  - ruby -v
  - which ruby
  - gem update --system
  - gem --version
  - gem install bundler
  - bundle -v
  - rm Gemfile.lock || true
  - bundle install --path vendor/bundle
script:
  - 'bundle exec $CHECK'
bundler_args:     --without system_tests
rvm:
  - 2.5.3
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet6 PUPPET_GEM_VERSION="~> 6.0"
matrix:
  fast_finish:    true
  include:
    -
      name:       "Puppet Lint"
      env:        CHECK="rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    -
      name:       "Doc Lint"
      env:        CHECK="mdl ."
    -
      name:       "Puppet 6 Spec"
      env:        PUPPET_GEM_VERSION="~> 6.0" CHECK="rake parallel_spec"
    -
      name:       "Puppet 5 Spec"
      env:        PUPPET_GEM_VERSION="~> 5.0" CHECK="rake parallel_spec"
      rvm:        2.4.5
branches:
  only:
    - master
    - stable
    - /^\d+\.\d+\.\d+/
notifications:
  email:          false
deploy:
  provider:       puppetforge
  user:           puppet
  password:
    secure:       ""
  on:
    tags:         true
    all_branches: true
    condition:    "$DEPLOY_TO_FORGE = yes"
